name: flutter_acs_card_reader
version: 1.0.7
description: A Flutter plugin to read cards on Advanced Card Systems readers through BLE.
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  plugin_platform_interface: ^2.1.6
  flutter_blue_plus: ^1.14.23
  permission_handler: 11.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.benjamin.horner.flutter_acs_card_reader
        pluginClass: FlutterAcsCardReaderPlugin
      ios:
        pluginClass: FlutterAcsCardReaderPlugin
